[build]
  # Change the command to execute the new shell script
  command = "bash build.sh"
  publish = "dist" 
  functions = "netlify/functions" 

[context.production.environment]
  NODE_VERSION = "18"